#数据源配置

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/blog3?useSSL=false&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 111111
# 关闭thymeleaf缓存
  thymeleaf:
    cache: false


  #视图解析器配置
  mvc:
    view:
      prefix: classpath*:/templates/
      suffix: .html
      #开启restful
    hiddenmethod:
      filter:
        enabled: true
#SpringBoot整合Email 邮件发送
#评论邮件回复配置
  mail:
    default-encoding: utf-8
# 主机地址
    host: smtp.163.com
# 邮箱名
    username: 1724048749@qq.com
# 授权码（不是密码）
    password: csxtrhgfemlvefbj
# redis配置
  redis:
    host: 192.168.157.132
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 100
        max-wait: 1
        max-idle: 10
        min-idle: 0
    timeout: 1000
    password: 111111

#mybatis-plus配置
mybatis-plus:
  configuration:
    #添加日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
#mybatis分页插件配置
pagehelper:
  #设置参数合理化
  reasonable: true

#日志配置
logging:
  lever:
    root: info
    com.heshijia: debug
  #配置日志文件存放路径
  file:
    path: log/blog/
server:
  port: 80


